### ISSUE TITLE
'tracks.pickle' and 'frames.pickle' of HighD dataset

### ISSUE THREAD

**Issue by panmengquan77** [SajjadMzf/TrajPred#2]
I can not find the 'tracks.pickle' and 'frames.pickle' of HighD dataset. Can you help me?

**Comment by SajjadMzf** [comment]
If you have access to the highD dataset, you wouldn't need to have .pickle files. These are the files created once you read the dataset CSV files using the code provided. For next runs, these pickle files can be used instead for faster read.
